on:
  push:
    branches:
    - master

jobs:
  update_submodule:
    name: Update submodule branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref:
            submodule
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull master
          git push
